src/rentalbuku/rental/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from django.views.generic.edit import DeleteView

from .views import *

app_name = 'rental-buku'


urlpatterns = [
    path('', Index.as_view(), name='index'),
    path('register', UserRegisterView.as_view(), name='register'),
    path('login', UserLoginView.as_view(), name='login'),
    path('logout', UserLogoutView.as_view(), name='logout'),

    path(
        'list', 
        login_required(ListBookView.as_view(), login_url='rental-buku:login'), 
        name='list'
    ),
    path(
        'add', 
        login_required(CreateBookView.as_view(), login_url='rental-buku:login'), 
        name='create'
    ),
    path(
        '<int:ID>', 
        login_required(DetailBookView.as_view(), login_url='rental-buku:login'), 
        name='detail'
    ),
    path(
        'update/<int:ID>', 
        login_required(UpdateBookView.as_view(), login_url='rental-buku:login'), 
        name='update'
    ),
    path(
        'delete/<int:ID>', 
        login_required(DeleteBookView.as_view(), login_url='rental-buku:login'), 
        name='delete'
    ),
]

src/rentalbuku/rentalbuku/urls.py
from django.contrib import admin
from django.urls    import path, include

urlpatterns = [
    path('rental/', include('rental.urls')),

    path('admin/', admin.site.urls),
]

src/rentalbuku/rental/models.py
from django.db import models
from django.db import models
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser


class Roles(models.Model):
    ID      = models.BigAutoField(primary_key=True)
    role    = models.CharField(max_length=20)

    def __str__(self) -> str:
        return self.role


class UserManager(BaseUserManager):
    def create_user(self, email, nama, no_telp, alamat, password=None):
        """
        Creates and saves a User with the given email and password.
        """
        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(
            nama=nama, 
            no_telp=no_telp, 
            alamat=alamat, 
            password=password,
            roles_id=Roles.objects.get(ID=2),
            email=self.normalize_email(email)
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_staffuser(self, nama, no_telp, alamat, email, password):
        """
        Creates and saves a staff user with the given email and password.
        """
        user = self.create_user(
            nama, no_telp, alamat, email, password
        )
        user.staff = True
        user.save(using=self._db)
        return user

    def create_superuser(self, nama, no_telp, alamat, email, password):
        """
        Creates and saves a superuser with the given email and password.
        """
        user = self.create_user(
            email, nama, no_telp, alamat, password,
        )
        user.staff = True
        user.admin = True
        user.save(using=self._db)
        return user

class User(AbstractBaseUser):
    ID          = models.BigAutoField(primary_key=True)
    nama        = models.CharField(max_length=100)
    email       = models.EmailField(unique=True)
    no_telp     = models.CharField(max_length=20)
    alamat      = models.TextField()
    password    = models.CharField(max_length=100)
    roles_id    = models.ForeignKey(Roles, on_delete=models.deletion.CASCADE)

    # BASE User Models
    is_active   = models.BooleanField(default=True)
    staff       = models.BooleanField(default=False)
    admin       = models.BooleanField(default=False)

    objects     = UserManager()

    USERNAME_FIELD  = 'email'
    REQUIRED_FIELDS = ['nama', 'no_telp', 'alamat', 'password'] 

    def get_full_name(self):
        return self.nama

    def get_short_name(self):
        return self.nama

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        return self.staff

    @property
    def is_admin(self):
        "Is the user a admin member?"
        return self.admin


class Genre(models.Model):
    ID          = models.BigAutoField(primary_key=True)
    genre       = models.CharField(max_length=20)

    def __str__(self) -> str:
        return self.genre

class Books(models.Model):
    ID          = models.BigAutoField(primary_key=True)
    genre_id    = models.ForeignKey(Genre, on_delete=models.deletion.CASCADE)
    judul_buku  = models.CharField(max_length=100)
    deskripsi   = models.TextField(blank=True, null=True)
    gambar      = models.FileField(upload_to='gambar', blank=True, null=True)
    harga       = models.CharField(max_length=100)
    pemilik_id  = models.ForeignKey(User, related_name="pemilik", on_delete=models.deletion.CASCADE)
    peminjam_id = models.ForeignKey(User, related_name="peminjam",on_delete=models.deletion.CASCADE)
    status      = models.BooleanField(default=False)
    publish     = models.DateField()

    def __str__(self) -> str:
        return self.judul_buku

src/rentalbuku/rental/forms.py
import datetime
from django                     import forms
from django.core.exceptions     import ValidationError
from django.contrib.auth        import authenticate, login
from django.contrib.auth.forms  import ReadOnlyPasswordHashField
from django.forms.models        import ModelChoiceField
from django.forms.widgets       import CheckboxInput, ChoiceWidget, DateInput, DateTimeInput, FileInput, HiddenInput, NumberInput, PasswordInput, RadioSelect, Select, SelectMultiple, TextInput, Textarea

from .models import *

# Form yang diperlukan adalah nama ,email, nomor telepon, alamat, dan password 
class UserRegisterForm(forms.ModelForm):
    
    # Edit fields in constructor
    # def __init__(self, *args, **kwargs):
    #     super(UserRegisterForm, self).__init__(*args, **kwargs)

    nama        = forms.CharField(
        max_length=100,
        widget=TextInput({'class':'forms-control'}), 
        required=True
    )
    email       = forms.EmailField(
        required=True,
        widget=TextInput({'class':'forms-control'}), 
    )
    no_telp     = forms.CharField(
        required=True,
        widget=NumberInput({'class':'forms-control'}),  
        label="Nomor Telepon"
    )
    alamat      = forms.CharField(
        widget=Textarea({'class': 'forms-control'}), 
        required=True
    )
    password    = forms.CharField(
        min_length=8,
        widget=PasswordInput({'class': 'forms-control'}),  
        required=True
    )
    password2   = forms.CharField(
        widget=PasswordInput({'class': 'forms-control'}),
        required=True,
        label="Konfirmasi password"
    )
    roles_id    = forms.CharField(
        required=False, 
        widget=HiddenInput()
    )

    class Meta:
        model   = User
        fields  = '__all__'

    def clean(self, *args, **kwargs):
        cleaned_data    = super().clean(*args, **kwargs)
        cleaned_data['roles_id'] = Roles.objects.get(ID=2)
        email           = cleaned_data.get('email')
        password        = cleaned_data.get('password')
        password2       = cleaned_data.get('password2')
        
        if User.objects.filter(email__iexact=email).exists():
            raise ValidationError("Email telah terdaftar")

        if password2 != password:
            raise ValidationError("Password tidak sama")

    def save(self, commit=True):
        user = super(UserRegisterForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user

class UserLoginForm(forms.Form):

    email       = forms.EmailField(
            required=True,
            widget=TextInput({'class':'forms-control'}), 
        )

    password    = forms.CharField(
            widget=PasswordInput({'class': 'forms-control'}),  
            required=True
        )

    def clean(self, *args, **kwargs):
        email           = self.cleaned_data.get('email')
        password        = self.cleaned_data.get('password')

        user            = authenticate(email=email, password=password)

        if not user:
            raise ValidationError('email atau password salah')
        

class AddBookForm(forms.ModelForm):

    genre_id    = forms.ModelChoiceField(
        queryset=Genre.objects.all(),
        initial=Genre.objects.get(ID=999),
        widget=Select({'class':'form-control'}),
        label="Genre buku"
    )
    judul_buku  = forms.CharField(
        max_length=100,
        widget=TextInput({'class':'form-control'}),
        required=True,
        label="Judul buku"
    )
    deskripsi   = forms.CharField(
        widget=Textarea({'class':'form-control'}),
        required=False
    )
    gambar      = forms.FileField(
        widget=FileInput({'class':'form-control-file'}),
        required=False
    )
    harga       = forms.CharField(
        widget=NumberInput({'class':'form-control'})
    )
    peminjam_id = forms.ModelChoiceField(
        queryset=User.objects.all(),
        widget=Select({'class':'form-control'}),
        label="Peminjam"
    )
    status      = forms.BooleanField(
        label='Sedang dipinjam',
        required=False
    )
    publish     = forms.DateField(
        initial=datetime.datetime.now().strftime("%Y-%m-%d"), 
        widget=DateInput(attrs={'type': 'date'})
    )
    pemilik_id    = forms.CharField(
        required=False, 
        widget=HiddenInput()
    )
    

    class Meta:
        model   = Books
        fields  = '__all__'

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super(AddBookForm, self).__init__(*args, **kwargs)

    def clean(self, *args, **kwargs):
        cleaned_data    = super().clean(*args, **kwargs)
        if not self.user:
            raise ValidationError('Hmmmm')
        if not cleaned_data['peminjam_id']:
            cleaned_data['peminjam_id'] = User.objects.get(ID=self.user.ID)
        cleaned_data['pemilik_id'] = User.objects.get(ID=self.user.ID)

        print(cleaned_data)

'''
Admin Forms
'''
class UserRolesForm(forms.ModelForm):

    role        = forms.CharField()

    class Meta:
        model   = User
        fields  = [
            'role'
        ]

class BookGenreForm(forms.ModelForm):

    genre        = forms.CharField()

    class Meta:
        model   = Genre
        fields  = [
            'genre'
        ]

class AdminCreateUserForm(forms.ModelForm):
    password   = forms.CharField(
            widget=PasswordInput({'class': 'forms-control'}),
            required=True,
            label="Konfirmasi password"
        )
    password2   = forms.CharField(
            widget=PasswordInput({'class': 'forms-control'}),
            required=True,
            label="Konfirmasi password"
        )
    class Meta:
        model   = User
        fields  = '__all__'

    def clean(self):
        cleaned_data    = super().clean()
        password        = cleaned_data.get("password")
        password2       = cleaned_data.get("password2")
        if password is not None and password != password2:
            raise ValidationError("Password tidak sama")
        return cleaned_data

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user

class AdminChangeUserForm(forms.ModelForm):
    """A form for updating users. Includes all the fields on
    the user, but replaces the password field with admin's
    password hash display field.
    """
    password = ReadOnlyPasswordHashField(
            help_text='<a href="../password/">Change</a>'
        )
    
    class Meta:
        model = User
        fields = '__all__'

    def clean_password(self):
        # Regardless of what the user provides, return the initial value.
        # This is done here, rather than on the field, because the
        # field does not have access to the initial value
        return self.initial["password"]

src/rentalbuku/rental/views.py
from django.shortcuts   import redirect, render
from django.views       import generic
from django.urls        import reverse_lazy
from django.contrib     import messages, auth

from .models            import *
from .forms             import *

'''
Users
'''
class UserRegisterView(generic.CreateView):
    model           = User
    form_class      = UserRegisterForm
    success_url     = reverse_lazy('rental-buku:index')
    template_name   = 'users/register.html'
    # success_message = "Registrasi berhasil"

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)
    
    def form_invalid(self, form):
        return super(UserRegisterView, self).form_invalid(form)

class UserLoginView(generic.edit.FormView):
    form_class      = UserLoginForm
    template_name   = 'users/login.html'
    success_url     = reverse_lazy('rental-buku:index')

    def form_valid(self, form):
        email       = self.request.POST['email']
        password    = self.request.POST['password']
        user        = auth.authenticate(email=email, password=password)
        if user is not None:
            auth.login(self.request, user)
            return super().form_valid(form)
        else:
            return redirect('rental-buku:login')

    def form_invalid(self, form):
        return super(UserLoginView, self).form_invalid(form)

class UserLogoutView(generic.RedirectView):
    url = '/rental/login'

    def get(self, request, *args, **kwargs):
        auth.logout(request)
        return super(UserLogoutView, self).get(request, *args, **kwargs)

'''
Books
'''
class ListBookView(generic.ListView):

    model           = Books
    paginated_by    = 5
    template_name   = 'books/list.html'

class CreateBookView(generic.CreateView):
    
    form_class      = AddBookForm
    template_name   = 'books/create.html'
    success_url     = reverse_lazy('rental-buku:index')

    def get_form_kwargs(self):
        kwargs = super(CreateBookView, self).get_form_kwargs()
        kwargs.update({'user': self.request.user})
        return kwargs

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

    def form_invalid(self, form):
        print('nah')
        messages.error(self.request, 'nah')
        return super(CreateBookView, self).form_invalid(form)

class DetailBookView(generic.DetailView):
    
    slug_url_kwarg  = "ID"
    slug_field      = "ID"
    model           = Books
    template_name   = 'books/detail.html'

class UpdateBookView(generic.UpdateView):
    
    slug_url_kwarg  = "ID"
    slug_field      = "ID"
    model           = Books
    template_name   = 'books/update.html'
    success_url     = reverse_lazy('rental-buku:list')

    fields = [
        'judul_buku',
        'harga',
        'deskripsi',
        'status',
        'publish',
    ]

class DeleteBookView(generic.DeleteView):
    
    slug_url_kwarg  = "ID"
    slug_field      = "ID"
    model           = Books
    template_name   = 'books/delete.html'
    success_url     = reverse_lazy('rental-buku:list')

class Index(generic.View):
    
    def get(self, request):
        return render(request, 'index.html')

src/rentalbuku/rental/templates/books/create.html
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>

{% block content %}
{% load crispy_forms_tags %} 
<section id="add-book" class="py-5 text-primary" style="margin-bottom: 80px;">
    <div class="container">
      <div class="row">
        <div class="col-md-6 mx-auto">
          <div class="card">
            <div class="card-header bg-primary text-white">
              <h4>
                <i class="fas fa-sign-in-alt"></i> Add Book</h4>
            </div>
            <div class="card-body">
                <form action="" method="POST">
                    {% csrf_token %}
                    {{ form | as_crispy_errors }}
                    {{ form.errors | as_crispy_errors }}
                    {{ form.non_field_errors | as_crispy_errors }}

                    <div class="form-group">
                        {{ form.genre_id | as_crispy_field }}
                    </div>
                    <div class="form-group">
                        {{ form.judul_buku | as_crispy_field }} 
                    </div>
                    <div class="form-group">
                        {{ form.deskripsi | as_crispy_field }}
                    </div>
                    <div class="form-group">
                        {{ form.gambar | as_crispy_field }} 
                    </div>
                    <div class="form-group">
                        {{ form.harga | as_crispy_field }}
                    </div>
                    <div class="form-group">
                        {{ form.peminjam_id | as_crispy_field }} 
                    </div>
                    <div class="form-group">
                        {{ form.status | as_crispy_field }}
                    </div>
                    <div class="form-group">
                        {{ form.publish | as_crispy_field }} 
                    </div>

                    <input type="submit" value="Add" class="btn btn-secondary btn-block">
                </form>
            </div>
          </div>
        </div>
      </div>
    </div>
</section>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
{% endblock content %}

src/rentalbuku/rental/templates/books/delete.html
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>

{% block content %}
{% load crispy_forms_tags %} 
<section id="add-book" class="py-5 text-primary" style="margin-bottom: 80px;">
    <div class="container">
      <div class="row">
        <div class="col-md-6 mx-auto">
          <div class="card">
            <div class="card-header bg-primary text-white">
                <h4>
                    <i class="fas fa-sign-in-alt"></i> Add Book
                </h4>
            </div>
            <div class="card-body">
                <form method="POST">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="">Hapus "{{ object }}" ini?</label>
                    </div>    
                    <input class="btn btn-primary" type="submit" value="Ya">
                </form>
            </div>
          </div>
        </div>
      </div>
    </div>
</section>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
{% endblock content %}

src/rentalbuku/rental/templates/books/detail.html
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>

{% block content %}
{% load crispy_forms_tags %} 
<section id="list-book" class="py-5 text-primary" style="margin-bottom: 80px;">
    <div class="card text-white bg-primary">
        <img class="card-img-top" src="{{ object.gambar }}" alt="">
        <div class="card-body">
            <h4 class="card-title">{{ object.judul_buku }}</h4>
            <p class="card-text">{{ object.harga }}</p>
            <p class="card-text">{{ object.pemilik_id }}</p>
            <p class="card-text">{{ object.peminjam_id }}</p>
            <p class="card-text">{{ object.status }}</p>
            <p class="card-text">{{ object.publish }}</p>
            <p class="card-text">{{ object.deskripsi }}</p>
            <a 
                class="btn btn-secondary" 
                href="{% url 'rental-buku:delete' object.ID %}" 
                role="button"
            >Delete
            </a>
        </div>
    </div>
</section>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
{% endblock content %}

src/rentalbuku/rental/templates/books/list.html
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>

{% block content %}
{% load crispy_forms_tags %} 
<section id="list-book" class="py-5 text-primary" style="margin-bottom: 80px;">
    <a class="btn btn-secondary" href="{% url 'rental-buku:create' %}" role="button">
        Tambah Buku
    </a>
    <div class="card-columns">
        {% for object in object_list %}
        <div class="card">
            <img class="card-img-top" src="holder.js/100x180/" alt="">
            <div class="card-body">
                <h4 class="card-title">{{ object.judul_buku }}</h4>
                <p class="card-text">{{ object.deskripsi }}</p>
                <a  class="btn btn-primary" 
                    href="{% url 'rental-buku:detail' object.ID %}" 
                    role="button"
                > Detail
                </a>
                <a  class="btn btn-primary" 
                    href="{% url 'rental-buku:update' object.ID %}" 
                    role="button"
                > Update
                </a>
            </div>
        </div>
        <hr/>
        {% empty %}
        <li>Nothing here</li>
        {% endfor %}
    </div>
</section>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
{% endblock content %}

src/rentalbuku/rental/templates/books/update.html
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>

{% block content %}
{% load crispy_forms_tags %} 
<section id="add-book" class="py-5 text-primary" style="margin-bottom: 80px;">
    <div class="container">
      <div class="row">
        <div class="col-md-6 mx-auto">
          <div class="card">
            <div class="card-header bg-primary text-white">
              <h4>
                <i class="fas fa-sign-in-alt"></i> Add Book</h4>
            </div>
            <div class="card-body">
                <form action="" method="POST">
                    {% csrf_token %}
                    {{ form | as_crispy_errors }}
                    {{ form.errors | as_crispy_errors }}
                    {{ form.non_field_errors | as_crispy_errors }}

                    <div class="form-group">
                        {{ form.judul_buku | as_crispy_field }} 
                    </div>
                    <div class="form-group">
                        {{ form.deskripsi | as_crispy_field }}
                    </div>
                    <div class="form-group">
                        {{ form.harga | as_crispy_field }}
                    </div>
                    <div class="form-group">
                        {{ form.status | as_crispy_field }}
                    </div>
                    <div class="form-group">
                        {{ form.publish | as_crispy_field }} 
                    </div>

                    <input type="submit" value="Update" class="btn btn-secondary btn-block">
                </form>
            </div>
          </div>
        </div>
      </div>
    </div>
</section>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
{% endblock content %}